// ---------------------------------------------------------------------------
// voice-agent — entry point.
//
// Phase 1: HTTP-only. Express handles the Telnyx webhook; no WS yet.
// Phase 2 will add a `ws` server upgrade for the audio bridge on the
// same http.Server instance — we already create that instance manually
// so Phase 2 is a one-import addition.
// ---------------------------------------------------------------------------
const http = require('http');
const express = require('express');

const config = require('./config');
const telnyxWebhook = require('./routes/telnyxWebhook');
const openaiTts = require('./services/openaiTts');

const app = express();

// Telnyx signs the RAW request body. We must capture the bytes
// untouched for verification — Express's default `express.json()` would
// re-stringify and break the signature. Use `express.raw` for the
// webhook path only and parse JSON ourselves inside the route handler.
app.use(
  '/api/telnyx/webhook',
  express.raw({ type: '*/*', limit: '1mb' }),
);

// All other routes get JSON parsing (e.g. /health, future admin pings).
app.use(express.json());

// Serve TTS audio buffers generated by openaiTts for Telnyx playback_start.
// Telnyx fetches the URL we hand it; Railway is public so this works fine.
//
// Telnyx is strict about audio HTTP responses: it issues a HEAD before
// GET and frequently sends Range requests. The original implementation
// only handled plain GET, which made Telnyx abandon the playback after
// ~1s (we observed playback.ended firing immediately). The handler
// below answers HEAD, full GET, and Range GET so playback runs to
// completion. The optional `.mp3` suffix in the URL keeps Telnyx's
// extension-based codec detection happy.
function serveAudio(req, res) {
  const key = (req.params.key || '').replace(/\.mp3$/i, '');
  const buf = openaiTts.getCached(key);
  if (!buf) return res.status(404).end();

  const total = buf.length;
  res.set('Content-Type', 'audio/mpeg');
  res.set('Accept-Ranges', 'bytes');
  res.set('Cache-Control', 'public, max-age=3600');

  // HEAD: headers only.
  if (req.method === 'HEAD') {
    res.set('Content-Length', total);
    return res.status(200).end();
  }

  const range = req.headers.range;
  if (range) {
    const match = /bytes=(\d*)-(\d*)/.exec(range);
    if (match) {
      const start = match[1] ? parseInt(match[1], 10) : 0;
      const end = match[2] ? parseInt(match[2], 10) : total - 1;
      if (Number.isNaN(start) || Number.isNaN(end) || start > end || end >= total) {
        res.set('Content-Range', `bytes */${total}`);
        return res.status(416).end();
      }
      const chunk = buf.subarray(start, end + 1);
      res.status(206);
      res.set('Content-Range', `bytes ${start}-${end}/${total}`);
      res.set('Content-Length', chunk.length);
      return res.end(chunk);
    }
  }

  res.set('Content-Length', total);
  res.status(200).end(buf);
}

// Both `/api/audio/:key` and `/api/audio/:key.mp3` work — the regex
// keeps the suffix optional so Telnyx URL-extension sniffing still picks
// up the right codec.
app.get('/api/audio/:key', serveAudio);
app.head('/api/audio/:key', serveAudio);

app.get('/health', (_req, res) => {
  res.json({
    ok: true,
    service: 'voice-agent',
    phase: 1,
    time: new Date().toISOString(),
  });
});

app.use('/api/telnyx', telnyxWebhook);

app.use((_req, res) => res.status(404).json({ error: 'not_found' }));

const server = http.createServer(app);

server.listen(config.port, () => {
  console.log(`[voice-agent] listening on :${config.port}`);
  if (!config.telnyx.apiKey) {
    console.warn('[voice-agent] TELNYX_API_KEY missing — Call Control commands will fail');
  }
  if (!config.telnyx.publicKey) {
    console.warn(
      '[voice-agent] TELNYX_PUBLIC_KEY missing — webhook signature verification is DISABLED',
    );
  }
  // Fire-and-forget — pre-generate greeting audio so the first inbound
  // call doesn't time out on TTS. See openaiTts.prewarmGreetings docstring.
  openaiTts.prewarmGreetings();
});

// Graceful shutdown so Railway rolling deploys don't drop calls.
function shutdown(signal) {
  console.log(`[voice-agent] received ${signal} — shutting down`);
  server.close(() => process.exit(0));
  // Hard exit after 10s in case a hung connection holds the close.
  setTimeout(() => process.exit(1), 10_000).unref();
}
process.on('SIGTERM', () => shutdown('SIGTERM'));
process.on('SIGINT', () => shutdown('SIGINT'));
